create extension if not exists pgcrypto;

create table if not exists public.portfolio_leads (
  id uuid primary key default gen_random_uuid(),
  first_name text,
  last_name text,
  email text not null,
  company text,
  job_title text,
  company_size integer,
  budget_range text,
  timeline text,
  source text,
  message text,
  deterministic_score integer not null default 0,
  ai_fit_score integer not null default 0,
  lead_score integer not null default 0,
  tier text not null check (tier in ('HOT','WARM','NURTURE','LOW')),
  ai_summary text,
  recommended_action text,
  approval_status text not null default 'not_required'
    check (approval_status in ('not_required','pending_human_approval','approved','rejected')),
  created_at timestamptz not null default now()
);

create index if not exists idx_portfolio_leads_email
on public.portfolio_leads(email);

create index if not exists idx_portfolio_leads_tier
on public.portfolio_leads(tier);

create table if not exists public.portfolio_lead_audit_log (
  id bigint generated by default as identity primary key,
  lead_email text not null,
  stage text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
